/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamento.view.gui;

import estacionamento.view.ICaixaView;
import java.awt.event.ActionListener;

/**
 *
 * @author flavio
 */
public class CaixaView extends javax.swing.JPanel implements ICaixaView {

    /**
     * Creates new form CaixaView
     */
    public CaixaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ocuparVaga = new javax.swing.JButton();
        ocuparVagaMensalista = new javax.swing.JButton();
        desocuparVaga = new javax.swing.JButton();
        desocuparVagaMensalista = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Caixa");

        ocuparVaga.setText("Ocupar Vaga");
        ocuparVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocuparVagaActionPerformed(evt);
            }
        });

        ocuparVagaMensalista.setText("Ocupar Vaga Mensalista");

        desocuparVaga.setText("Desocupar Vaga");
        desocuparVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desocuparVagaActionPerformed(evt);
            }
        });

        desocuparVagaMensalista.setText("Desocupar Vaga Mensalista");
        desocuparVagaMensalista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desocuparVagaMensalistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(desocuparVaga)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(desocuparVagaMensalista)
                        .addGap(83, 83, 83))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ocuparVagaMensalista)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ocuparVaga)
                        .addGap(134, 134, 134))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(ocuparVaga)
                .addGap(18, 18, 18)
                .addComponent(ocuparVagaMensalista)
                .addGap(18, 18, 18)
                .addComponent(desocuparVaga)
                .addGap(18, 18, 18)
                .addComponent(desocuparVagaMensalista)
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ocuparVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocuparVagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ocuparVagaActionPerformed

    private void desocuparVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desocuparVagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desocuparVagaActionPerformed

    private void desocuparVagaMensalistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desocuparVagaMensalistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desocuparVagaMensalistaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton desocuparVaga;
    private javax.swing.JButton desocuparVagaMensalista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ocuparVaga;
    private javax.swing.JButton ocuparVagaMensalista;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addOuvinteOcuparVaga(ActionListener ouvinte) {
        ocuparVaga.addActionListener(ouvinte);
    }

    @Override
    public void addOuvinteOcuparVagaMensalista(ActionListener ouvinte) {
        ocuparVagaMensalista.addActionListener(ouvinte);
    }

    @Override
    public void addOuvinteDesocuparVaga(ActionListener ouvinte) {
        desocuparVaga.addActionListener(ouvinte);
    }

    @Override
    public void addOuvinteDesocuparVagaMensalista(ActionListener ouvinte) {
        desocuparVagaMensalista.addActionListener(ouvinte);
    }
}
