/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamento.view.gui;

import estacionamento.view.ILiberarVagaView;
import java.awt.event.ActionListener;

/**
 *
 * @author gustavo
 */
public class LiberarVagaView extends javax.swing.JPanel implements ILiberarVagaView
{

    /**
     * Creates new form LiberarVagaView
     */
    public LiberarVagaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldPlaca = new javax.swing.JTextField();
        labelEntrada = new javax.swing.JLabel();
        labelSaida = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        bLiberar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        labelCPF = new javax.swing.JLabel();

        fieldPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPlacaActionPerformed(evt);
            }
        });

        labelEntrada.setText("Horário de entrada");

        labelSaida.setText("Horário de saída");

        labelValor.setText("Valor a ser pago");

        bLiberar.setText("Liberar Vaga");

        jLabel4.setText("Liberar Vaga");

        labelCPF.setText("Placa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(labelCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEntrada)
                    .addComponent(labelSaida)
                    .addComponent(labelValor)
                    .addComponent(bLiberar)
                    .addComponent(jLabel4))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(labelCPF))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(fieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(58, 58, 58)
                                .addComponent(labelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelSaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelValor)
                                .addGap(18, 18, 18)
                                .addComponent(bLiberar)))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPlacaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLiberar;
    private javax.swing.JTextField fieldPlaca;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelEntrada;
    private javax.swing.JLabel labelSaida;
    private javax.swing.JLabel labelValor;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getPlaca() {
        return fieldPlaca.getText();
    }

    @Override
    public void addOuvinteOk(ActionListener ouvinte) {
        bLiberar.addActionListener(ouvinte);
    }
}
