/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamento.view.gui;

import estacionamento.view.IOcuparVagaView;
import java.awt.event.ActionListener;

/**
 *
 * @author gustavo
 */
public class OcupaVagaView extends javax.swing.JPanel implements IOcuparVagaView {

    /**
     * Creates new form OcupaVagaView
     */
    public OcupaVagaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bOcupaVaga = new javax.swing.JButton();
        fieldModelo = new javax.swing.JTextField();
        labelOcupaVaga = new javax.swing.JLabel();
        fieldCor = new javax.swing.JTextField();
        fieldPlaca = new javax.swing.JTextField();

        bOcupaVaga.setText("Ocupar Vaga");
        bOcupaVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOcupaVagaActionPerformed(evt);
            }
        });

        fieldModelo.setText("Modelo");
        fieldModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldModeloActionPerformed(evt);
            }
        });

        labelOcupaVaga.setText("Ocupar Vaga");

        fieldCor.setText("Cor");
        fieldCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCorActionPerformed(evt);
            }
        });

        fieldPlaca.setText("Placa");
        fieldPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPlacaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(labelOcupaVaga))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(fieldPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(fieldCor, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(bOcupaVaga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelOcupaVaga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(fieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bOcupaVaga)
                .addContainerGap(101, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldModeloActionPerformed

    private void fieldCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCorActionPerformed

    private void fieldPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPlacaActionPerformed

    private void bOcupaVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOcupaVagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bOcupaVagaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOcupaVaga;
    private javax.swing.JTextField fieldCor;
    private javax.swing.JTextField fieldModelo;
    private javax.swing.JTextField fieldPlaca;
    private javax.swing.JLabel labelOcupaVaga;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getPlaca() {
        return fieldPlaca.getText();
    }

    @Override
    public String getCor() {
        return fieldCor.getText();
    }

    @Override
    public String getModelo() {
        return fieldModelo.getText();
    }

    @Override
    public void addOuvinteOk(ActionListener ouvinte) {
        bOcupaVaga.addActionListener(ouvinte);
    }
}
